feat: #994 add price monitoring bounds and candles update interface
vegaprotocol/frontend-monorepo pull request #1050
Opened 2022-08-16 12:20 UTC by MadalinaRaicu

# Related issues 🔗

Closes #994 

# Description ℹ️

Add few missing details from market information such as price monitoring bounds and 24h volume

# Demo 📺

# Technical 👨‍🔧

2022-08-19 08:05 UTC, MadalinaRaicu commented on apps/trading-e2e/src/integration/market-info.cy.ts
> -    validateMarketDataRow(0, 'Indicative Volume', '0');
removing some tests - best bid volumes might be taken out of market info soon

2022-08-19 08:17 UTC, mattrussell36 approved these changes

2022-08-19 08:51 UTC, notbot00 commented on libs/deal-ticket/src/components/info-market.tsx
> +export const calcCandleVolume = (m: any): string | undefined => {
chore (blocking): i think the market type should be generated, you don't have to use any for it

2022-08-19 08:52 UTC, notbot00 commented on libs/deal-ticket/src/components/info-market.tsx
> +export const calcCandleVolume = (m: any): string | undefined => {
found it:

```suggestion
export const calcCandleVolume = (m: MarketInfoQuery_market): string | undefined => {
```

2022-08-19 09:06 UTC, notbot00 approved these changes

2022-08-19 09:32 UTC, dexturr commented on libs/deal-ticket/src/components/info-market-query.ts
> +        updateFrequencySecs
chore (blocking): this field no longer exists on testnet, remove please

2022-08-19 09:32 UTC, dexturr requested changes
Minor ting

2022-08-19 09:47 UTC, dexturr approved these changes

2022-08-23 17:43 UTC, candida-d commented on libs/deal-ticket/src/components/__generated__/MarketInfoQuery.ts
> +   * breach it's theoretical level over the specified horizon at the specified
this should be 'its', not 'it is'

2022-08-23 17:44 UTC, candida-d commented on libs/deal-ticket/src/components/__generated__/MarketInfoQuery.ts
> +   * breach it's theoretical level over the specified horizon at the specified
```suggestion
   * breach its theoretical level over the specified horizon at the specified
```

2022-08-23 17:44 UTC, candida-d commented on libs/deal-ticket/src/components/__generated__/MarketInfoQuery.ts
> +   * breach it's theoretical level over the specified horizon at the specified
Is this coming from the API?

2022-08-23 17:57 UTC, MadalinaRaicu commented on libs/deal-ticket/src/components/__generated__/MarketInfoQuery.ts
> +   * breach it's theoretical level over the specified horizon at the specified
it's coming from the API

2022-08-23 19:43 UTC, mattrussell36 approved these changes

2022-08-23 19:43 UTC, merged