[#185] Add accounts table
vegaprotocol/frontend-monorepo pull request #193
Opened 2022-04-01 11:52 UTC by bglownia

closes #185

2022-04-01 14:54 UTC, mattrussell36 approved these changes
Good stuff!

2022-04-04 09:12 UTC, dexturr approved these changes

2022-04-04 18:49 UTC, mattrussell36 requested changes

2022-04-04 18:49 UTC, mattrussell36 commented on libs/accounts/tsconfig.lib.json
> +    "../react-helpers/src/lib/grid-cells/summary-row.spec.ts"
Can remove

2022-04-04 18:49 UTC, mattrussell36 commented on libs/accounts/src/lib/accounts-table.tsx
> +      return data.asset.symbol;
We should probably use asset.id for this. Its extremely unlikely but in theory I think we could end up with duplicate asset symbols

2022-04-05 13:59 UTC, mattrussell36 approved these changes

2022-04-06 17:48 UTC, merged