frontend-monorepo-267 Reduce total staked to 2 decimal precision
vegaprotocol/frontend-monorepo pull request #282
Opened 2022-04-20 14:13 UTC by sam-keen

Closes #267

2022-04-20 14:32 UTC, dexturr requested changes
![Screenshot 2022-04-20 at 15 31 36](https://user-images.githubusercontent.com/26136207/164254512-347d1d40-7dff-4eb7-807a-1c222c165ed8.png)

We need to add a format decimal places to the number format function, this should set both minDecimals and maxDecimals in number.intl to ensure that it always renders the passed in number of d.p. probably want this to default to number of decimals to add to the number

2022-04-21 15:47 UTC, dexturr commented on libs/react-helpers/src/lib/format/number.ts
> +  decimalPrecision?: number
I forget the synax for default with TS so double check this but: suggest defaulting here

```suggestion
  decimalPrecision = decimals: number
```

2022-04-21 17:48 UTC, dexturr approved these changes

2022-04-25 14:24 UTC, edd approved these changes

2022-04-25 14:28 UTC, merged