feat(ui-toolkit, explorer): navigation
vegaprotocol/frontend-monorepo pull request #3069
Opened 2023-03-02 18:04 UTC by asiaznik

# Related issues 🔗

Closes #2840 
Closes #2936 

# Demo 📺

TBD

2023-03-06 15:05 UTC, edd requested changes

2023-03-06 15:05 UTC, edd commented on libs/ui-toolkit/src/components/drawer/drawer.tsx
>  export function Drawer({
**nitpick (blocking)**: Scolling can get weird on mobile - although here I am testing with Firefox, so if the issue doesn't show up on iOS safari/Chrome it's less blocking.

https://user-images.githubusercontent.com/6678/223148594-0df312c3-3c07-4b38-af67-aad58d1a4ed2.mov

2023-03-07 13:31 UTC, asiaznik commented on apps/explorer/src/app/components/header/header.tsx
> +  const isOnOther = useMemo(() => {
I've added an in-code comment explaining what is it for.

2023-03-10 14:07 UTC, edd approved these changes

2023-03-10 14:10 UTC, asiaznik commented on apps/explorer/src/app/app.tsx
> +const MainnetSimAd = () => (
Yup, let's do it later!

2023-03-10 15:46 UTC, merged