Feat/258 move key value table into monorepo
vegaprotocol/frontend-monorepo pull request #320
Opened 2022-04-27 16:25 UTC by MadalinaRaicu

2022-04-28 08:29 UTC, MadalinaRaicu commented on apps/token/src/routes/governance/components/proposal-change-table/proposal-change-table.tsx
> +      <KeyValueTableRow muted={true}>
muted and numerical tailwind styling has been added directly on `tr`,  `td` and `th` tags. This is why these props have been moved to KeyValueTableRows. I am looking into passing these props to the children.

2022-04-28 09:40 UTC, MadalinaRaicu commented on apps/token/src/routes/claim/claim-flow.tsx
> +                {t('Connected Ethereum address')}
`<th>` and `<td>` tags have been moved inside KeyValueTableRow and tailwind styling has been applied to them.

2022-04-28 10:35 UTC, MadalinaRaicu commented on apps/token/src/routes/home/token-details/token-details-circulating.tsx
> +    <span data-testid="circulating-supply">
spotted this. reverting it now.

2022-04-28 11:23 UTC, dexturr requested changes
Looking good, just a few minor things 👍

2022-04-28 12:10 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/index.ts
> +export { KeyValueTable, KeyValueTableRow } from './components/key-value-table';
resolved in my last commit

2022-04-28 12:10 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +      className={`flex flex-col sm:table-row border-b first:border-t border-white ${
resolved in last commit

2022-04-28 12:11 UTC, MadalinaRaicu commented on apps/token/src/routes/governance/components/proposal-votes-table/proposal-votes-table.tsx
> +        <span>{formatNumber(yesPercentage, 2)}%</span>
created a util function in last commit

2022-04-28 13:36 UTC, MadalinaRaicu commented on libs/tailwindcss-config/src/theme.js
> +    grey: {
black-40 or black-60 have low opacity and on dark theme they get invisible 
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/16125548/165764691-034f4db4-4d37-4533-bf70-479704d3d1fe.png">

2022-04-28 14:11 UTC, sam-keen requested changes

2022-04-28 14:11 UTC, sam-keen commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +        className={`w-full border-collapse mb-2.5 [border-spacing:0] break-all ${
Chore (blocking): Our custom Tailwind theme means the values you've used here with decimals won't work. The currently allowed spacings are defined in libs/tailwindcss-config/src/theme.js. If you need a custom value, use the square bracket syntax, i.e. mb-[0.3rem]. 

Question: not seen the syntax for what you've done here with `[border-spacing:0]`. What does this do?

2022-04-28 14:59 UTC, MadalinaRaicu commented on apps/token/src/routes/governance/components/proposals-list/proposals-list.tsx
> +            <span data-testid="governance-proposal-enactmentDatetime">
thanks for spotting this. updated in last commit.

2022-04-28 15:00 UTC, MadalinaRaicu commented on apps/token/src/routes/redemption/home/vesting-table.tsx
>              <div className="vesting-table__indicator-square vesting-table__indicator-square--locked"></div>
I have replaced the nested divs with spans in the last commit.

2022-04-28 15:06 UTC, sam-keen commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +        className={`w-full border-collapse mb-2.5 [border-spacing:0] break-all ${
Ah that's good to know, thanks!

2022-04-29 06:50 UTC, bglownia requested changes

2022-04-29 06:50 UTC, bglownia commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +    'flex flex-col sm:table-row border-b first:border-t border-white',
Text is also not visible ;(

2022-04-29 08:10 UTC, dexturr commented on README.md
> +Run `yarn nx run <my-app>-e2e:e2e --watch` to execute the unit tests with [Jest](https://jestjs.io) in watch mode. Use `nx affected:test` to execute just unit tests affected by a change.
```suggestion
Run `yarn nx run <my-app>-e2e:e2e` to execute the e2e tests with [cypress](https://docs.cypress.io/).  You can use the `--watch` flag to open the cypress tests UI in watch mode, see [cypress executor](https://nx.dev/packages/cypress/executors/cypress) for all CLI flags.

Run `nx test my-app` to execute the unit tests with [Jest](https://jestjs.io), or `nx affected:test` to execute just unit tests affected by a change. You can also use `--watch` with these test to run jest in watch mode, all CLI flags can be found in the [Jest executor documentation](https://nx.dev/packages/jest/executors/jest)
```

2022-04-29 08:48 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +  const tdClassName = classNames('align-top p-4 text-right text-grey', {
thanks for the clarification, I have updated the colors in my last commit.

2022-04-29 09:19 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +    'flex flex-col sm:table-row border-b first:border-t border-white',
thanks for the clarification. colors are updated in my last commit.

2022-04-29 09:25 UTC, MadalinaRaicu commented on libs/tailwindcss-config/src/theme.js
> +    grey: {
thanks for the clarification. colors are updated in the last commit.

2022-04-29 09:35 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +    <tr {...rest} className={trClassName}>
on it 👍

2022-04-29 09:35 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +      {title && <h3 className="mt-8 mb-4">{title}</h3>}
in my last commit I am also using the headingLevel prop to update the `text-h*` class

2022-04-29 09:37 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +        <TitleTag className={`text-h${headingLevel} mt-8 mb-4`}>
`text-h${headingLevel}` is required to reflect the proper header styling.

2022-04-29 09:59 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/key-value-table/key-value-table.tsx
> +    <tr {...rest} className={trClassName}>
updated to use `dl`. but, I can't apply the `{...rest}` on `dl`. I hope it is ok to remove it for now.

2022-04-29 11:30 UTC, bglownia approved these changes

2022-04-29 12:51 UTC, MadalinaRaicu commented on .prettierignore
> +*.md
format didn't like `md` files

2022-04-29 12:52 UTC, dexturr approved these changes

2022-04-29 13:18 UTC, sam-keen approved these changes

2022-04-29 13:27 UTC, merged