chore: add key hold handlers for conditionally external link
vegaprotocol/frontend-monorepo pull request #3273
Opened 2023-03-24 12:57 UTC by macqbat

# Related issues 🔗

Closes #3188 

# Description ℹ️

Make conditionally external link: CMD/Control + click should open market in new tab/window 

# Demo 📺

Gif/video/images of new/corrected functionality if applicable

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2023-03-28 13:03 UTC, MadalinaRaicu approved these changes

2023-03-29 05:06 UTC, mattrussell36 requested changes
Sorry @macqbat I don't think we should merge this. IMO We shouldn't make libs depend on a specific router implementation (IE using react-router-dom directly in libs). This makes re-use harder and complicates testing. I don't see any problem with just passing props.

Can we just make the simple change for now (and ensure its tested) and check for the meta key in the callback?

If we really want to avoid passing props, I'd recommend passing the `navigate` function down from the app using a context, that way the app can provide a specific navigate function

2023-03-29 07:46 UTC, macqbat commented
> Sorry @macqbat I don't think we should merge this. IMO We shouldn't make libs depend on a specific router implementation (IE using react-router-dom directly in libs). This makes re-use harder and complicates testing. I don't see any problem with just passing props.
> 
> Can we just make the simple change for now (and ensure its tested) and check for the meta key in the callback?
> 
> If we really want to avoid passing props, I'd recommend passing the `navigate` function down from the app using a context, that way the app can provide a specific navigate function

OK, I've reverted the commit where I pushed this simplification, since I placed it totally in one commit it was quite easy. However  In my opinion it was quite useful solution, and If in the future it would turn out as problematic, we could easily reformat the hook only to be more "router solution independent". 
Now again we pass from top to bottom through almost the entire component tree of the trading and wallet pages two different, almost identical handlers :-(

2023-03-30 05:11 UTC, mattrussell36 requested changes

2023-03-30 05:11 UTC, mattrussell36 commented on libs/datagrid/src/lib/cells/market-name-cell.tsx
> +    <Link to={marketLink} onClick={handleOnClick}>
chore (blocking): We should remove the dependency on react-router-dom here. I'd suggest just using a span but with appropriate attributes
```suggestion
    <span onClick={handleOnClick} role="link" tabIndex="0">
```

2023-03-30 05:11 UTC, mattrussell36 commented on libs/datagrid/src/lib/cells/market-name-cell.tsx
> +  const marketLink = `/${MARKET_PATH}/${id}`;
chore (blocking): remove router implementation details. Lets just use the onMarketClick callback and not render a link with a url

2023-03-30 05:19 UTC, mattrussell36 commented
Thanks for changing :-)

I don't understand the aversion to passing props (in most cases its 3/4 levels). It keeps things much simpler. 

I'd rather not have to wrap tests with MemoryRouter (or other contexts) for them to work and keep components more pure.

If you are concerned with the identical click handler logic perhaps make a hook `useMarketClickHandler` to share that logic

2023-03-31 13:23 UTC, merged