feat(trading): include fees in transfer amount
vegaprotocol/frontend-monorepo pull request #3345
Opened 2023-04-03 11:29 UTC by MadalinaRaicu

# Related issues 🔗

Closes #3248 

# Description ℹ️
Show total as transfer amount plus fees.

# Demo 📺

<img width="1177" alt="Screenshot 2023-04-03 at 12 23 52" src="https://user-images.githubusercontent.com/16125548/229496602-ee4bbc87-02b6-437c-8265-683dd2541f5a.png">
<img width="1171" alt="Screenshot 2023-04-03 at 12 22 41" src="https://user-images.githubusercontent.com/16125548/229496658-80356684-61d7-4f0f-b521-2b131cd952ed.png">

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2023-04-03 13:38 UTC, MadalinaRaicu commented on apps/trading/lib/hooks/use-vega-transaction-toasts.tsx
> +              rejectionReason || tx.order.rejectionReason,
```suggestion
              rejectionReason,
```

2023-04-03 13:39 UTC, MadalinaRaicu commented on apps/trading/lib/hooks/use-vega-transaction-toasts.tsx
> +        {rejectionReason || tx.order.rejectionReason ? (
```suggestion
        {rejectionReason ? (
```

2023-04-03 21:13 UTC, mattrussell36 requested changes
So this ticket was more about providing a way to allow users to transfer a specific amount, including fees, so that they don't need to calculate what amount will completely empty an account. What I think we should do is

Add a checkbox 'Include feeds'. If checked we set the transaction amount based on the user entered value minus the fee amount. So if a user enters an amount of 120 with a fee factor of 0.01, when we submit the tx we submit it with an amount of 118.8 (amount = input * (1 - feeFactor)

This way the total amount coming out of the account is 120 including fees.

2023-04-04 22:46 UTC, mattrussell36 requested changes

2023-04-04 22:46 UTC, mattrussell36 commented on libs/accounts/src/lib/transfer-form.spec.tsx
chore (blocking): can we add test coverage for use of the include fee checkbox

2023-04-05 09:28 UTC, MadalinaRaicu commented on libs/accounts/src/lib/transfer-form.spec.tsx
yes, it's still in draft mode

2023-04-07 06:55 UTC, mattrussell36 approved these changes

2023-04-07 06:55 UTC, mattrussell36 commented on libs/accounts/src/lib/transfer-form.spec.tsx
> +      const errors = screen.getAllByTestId('input-error-text');
suggestion (non blocking): this can be made more succinct (and no nesting with `const errors = await screen.findAllByTestId(...)`

2023-04-07 17:00 UTC, merged