fix(trading): order tx toasts title and intent should be set by status
vegaprotocol/frontend-monorepo pull request #3368
Opened 2023-04-04 15:47 UTC by MadalinaRaicu

# Related issues 🔗

Closes N/A

# Description ℹ️

Transaction toasts - the title should be set based on order status.

# Demo 📺

Fixing this:
![image](https://user-images.githubusercontent.com/16125548/229846676-57127e0e-b9f4-4e82-900f-21f833b5bc77.png)

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2023-04-04 15:47 UTC, MadalinaRaicu commented on apps/trading/lib/hooks/use-vega-transaction-toasts.tsx
> +  getOrderTitle as getOrderTitle,
```suggestion
  getOrderTitle,
```

2023-04-04 22:53 UTC, mattrussell36 requested changes

2023-04-04 22:53 UTC, mattrussell36 commented on libs/orders/src/lib/order-hooks/use-order-submit.tsx
> +export const getOrderTitle = (
chore (blocking): This file was a dead file. Can we 

a) move these helper functions to libs/orders/src/lib/utils.ts
b) rename to getOrderToastTitle etc etc
c) delete this file and corresponding test file

2023-04-07 06:55 UTC, mattrussell36 approved these changes

2023-04-07 17:01 UTC, merged