Feature/vega core
vegaprotocol/frontend-monorepo pull request #376
Opened 2022-05-05 11:55 UTC by elmar-vega

This PR is to add the bare functionality and setup for the simple trading app (name change pending).
We are using many of the components from the deal-ticket library and have kept refactors to a minimal. There should be no breaking changes for the other apps and where refactoring has taken place, the defaults have been kept.

2022-05-06 08:29 UTC, dexturr requested changes

2022-05-06 08:29 UTC, dexturr commented on apps/simple-trading-app/project.json
> +{
chore (blocking): somewhere in here you will need to set a different port from default for testing purposes, as the test run in parallel if everything tries to start on the same port we get errors

2022-05-06 08:29 UTC, dexturr commented on libs/deal-ticket/src/index.ts
> +export * from './expiry-selector';
question (non-blocking): why are we now exporting everything?

2022-05-06 13:05 UTC, mattrussell36 commented on apps/simple-trading-app/src/app/components/deal-ticket/deal-ticket-container.tsx
> +        <DealTicketManager market={data.market}>
suggestion (non-blocking) This is almost identical to deal-ticket-container in the lib/deal-ticket. Perhaps we add a render prop so we can provide different form components to be rendered but allow the 'container' to make the fetch request and the 'manager' to handle order state..

Something like:
```
// simple-trading-app
<DealTicketContainer
  render={({ market, submit }) => <DealTicketSteps market={market} submit={submit} />}
/>
// trading
<DealTicketContainer
  render={({ market, submit }) => <DealTicket market={market} submit={submit} />}
/>

```

2022-05-09 06:39 UTC, macqbat approved these changes

2022-05-09 06:39 UTC, macqbat commented on apps/simple-trading-app/project.json
> +      "executor": "@nrwl/web:webpack",
So finally are we sure, we don't want to do it as next.js?

2022-05-09 06:39 UTC, macqbat commented on package.json
> +    "@mui/material": "^5.6.2",
non-blocking: Do we really need this package (another one set of components) similar to blueprintjs and internal ui-toolkit? Wouldn't it be better to keep one "component facilitator" than many of them in one repo?

2022-05-09 06:39 UTC, macqbat commented on package.json
> +    "@mui/material": "^5.6.2",
moreover, tailwind.css alone offers many possibilities

2022-05-09 17:21 UTC, mattrussell36 approved these changes

2022-05-10 08:26 UTC, dexturr approved these changes

2022-05-12 09:56 UTC, merged