test(trading): 6001-MARK-find_markets e2e tests
vegaprotocol/frontend-monorepo pull request #4025
Opened 2023-06-02 13:18 UTC by daro-maj

# Related issues 🔗

Closes #3504 
Closes #3505 

# Description ℹ️

6001-MARK-find_markets e2e tests

2023-06-02 15:36 UTC, ben-vegaprotocol requested changes
Looks good!

2023-06-02 15:36 UTC, ben-vegaprotocol commented on apps/trading-e2e/src/integration/market-all.cy.ts
> +  it('can see table headerss', () => {
```suggestion
  it('can see table headers', () => {
```

2023-06-02 19:45 UTC, MadalinaRaicu approved these changes

2023-06-05 07:25 UTC, ben-vegaprotocol approved these changes

2023-06-05 07:25 UTC, merged