fix(trading): network switcher - update some css
vegaprotocol/frontend-monorepo pull request #4057
Opened 2023-06-08 08:29 UTC by macqbat

# Related issues 🔗

Closes #3704 

# Description ℹ️

Tweak some css for better ux

# Demo 📺

-

# Technical 👨‍🔧

-

2023-06-09 01:49 UTC, mattrussell36 requested changes

2023-06-09 12:51 UTC, macqbat commented on libs/environment/src/components/network-switcher/network-switcher.tsx
> +                className="p-0"
yeah, I merged it to fix/4058-dropdown-closing-market-list

2023-06-09 14:40 UTC, macqbat commented on libs/environment/src/components/network-switcher/network-switcher.tsx
> +                className="p-0"
done

2023-06-10 00:47 UTC, mattrussell36 commented
@macqbat have a look at my last few commits which fix act warning, actually by removing use of act completely

2023-06-10 01:27 UTC, mattrussell36 approved these changes

2023-06-10 14:48 UTC, merged