chore(trading): table actions dropdown alignments, default asset for account history, fixes asset selector for transfer dialog
vegaprotocol/frontend-monorepo pull request #4239
Opened 2023-07-03 17:01 UTC by asiaznik

# Related issues 🔗

Closes #3984
Closes #3911 
Closes #3972

# Description ℹ️

* table actions trigger is now highlighted when dropdown is open
* changed table actions labels
* added info icon to the vega icons collection
* added default asset for account history tab
* chosen asset for account history is not persisted in local storage
* fixed asset selector for transfer dialog

2023-07-04 11:59 UTC, bglownia requested changes

2023-07-04 11:59 UTC, bglownia commented on libs/accounts/src/lib/transfer-container.tsx
> +        balance: toBigNum(account.balance, account.asset.decimals),
I'm not a fan of using BigNum. Reason why is that they are harder to compare when used as memo param.
`new BigNumber(0) !== new BigNumber(0)`

2023-07-04 11:59 UTC, bglownia commented on libs/accounts/src/lib/transfer-form.tsx
> +                    <Balance balance={a.balance.toString()} symbol={a.symbol} />
formatNumber and new BigNumber().toString() will give different results.  We should always use formatNumber

2023-07-04 11:59 UTC, bglownia commented on libs/orders/src/lib/components/order-actions-dropdown/order-actions-dropdown.tsx
> +          className="hover:bg-vega-light-200 dark:hover:bg-vega-dark-200 [&.open]:bg-vega-light-200 dark:[&.open]:bg-vega-dark-200 p-0.5 rounded-full"
This repeats in many places. I suggest to make component from it `<ActionMenuTrigger />`

2023-07-04 12:26 UTC, asiaznik commented on libs/orders/src/lib/components/order-actions-dropdown/order-actions-dropdown.tsx
> +      onOpenChange={(open) => {
🤦🏻

2023-07-05 11:00 UTC, bglownia approved these changes

2023-07-05 11:02 UTC, merged