chore(transfer, withdraws): standalone pages for withdrop and transfer
vegaprotocol/frontend-monorepo pull request #4728
Opened 2023-09-07 15:35 UTC by macqbat

# Related issues 🔗

Issue: #4646 & #4647 
# Description ℹ️

Dedicated pages fot transfer and withdrawal tickets. Contains handling of assetId pass and clear it for not breaking the params state

# Demo 📺

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/338931/095efdc0-5547-4f6e-b874-aa002f059334)
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/338931/7b3e1fae-9a53-4b00-8407-ee8eedc831fe)

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2023-09-08 22:42 UTC, mattrussell36 requested changes

2023-09-08 22:42 UTC, mattrussell36 commented on apps/trading/client-pages/transfer/transfer.tsx
> +  const selectedAssetId = useTransferAssetIdStore((store) => store.assetId);
I don't see any purpose for the useTransferAssetIdStore.

2023-09-08 22:42 UTC, mattrussell36 commented on apps/trading/client-pages/withdraw/withdraw.tsx
> +      setSearchParams({});
I don't think we need to worry about clearing the url if the asset changes.

2023-09-08 22:42 UTC, mattrussell36 commented on apps/trading/pages/client-router.tsx
> +const LazyWithdraw = dynamic(() => import('../client-pages/withdraw'), {
I'd like to move away from using next/dynamic and even React.lazy in favor of just having a single js bundle. This makes things easier with ipfs and the benefits we gain from code splitting are minimal due to the nature of this being more app-like

2023-09-08 22:42 UTC, mattrussell36 commented on apps/trading/pages/client-router.tsx
> +  { path: Routes.WITHDRAW, element: <LazyWithdraw /> },
(non blocking): We should probably wrap these with a layout route to ensure consistency

2023-09-08 22:42 UTC, mattrussell36 commented on libs/accounts/src/lib/transfer-form.tsx
> +export const useTransferAssetIdStore = create<TransferAssetIdStore>()(
I think this store is unneccessary

2023-09-08 22:49 UTC, mattrussell36 commented on apps/trading/client-pages/transfer/transfer.spec.tsx
> +    <VegaWalletContext.Provider value={mockWalletContext}>
This is not needed as the container is mocked

2023-09-08 23:05 UTC, mattrussell36 commented on apps/trading/client-pages/transfer/transfer.spec.tsx
> +    <VegaWalletContext.Provider value={mockWalletContext}>
Actually it was needed for the GetStarted component, but I think it simpler to mock it. I've pushed changes

2023-09-08 23:06 UTC, mattrussell36 commented on apps/trading/pages/client-router.tsx
> +  { path: Routes.WITHDRAW, element: <LazyWithdraw /> },
I'll make an additional PR for this

2023-09-08 23:06 UTC, mattrussell36 commented on libs/accounts/src/lib/transfer-form.tsx
> +export const useTransferAssetIdStore = create<TransferAssetIdStore>()(
Having a whole new store to clear the query string is overkill.

2023-09-08 23:06 UTC, mattrussell36 commented on apps/trading/pages/client-router.tsx
> +const LazyWithdraw = dynamic(() => import('../client-pages/withdraw'), {
I've changed these to just be imported in a regular fashion. I'll make an additional PR to convert the rest

2023-09-08 23:10 UTC, mattrussell36 approved these changes

2023-09-11 08:36 UTC, bwallacee commented
@macqbat On the withdraws page, if I disconnect my etherum wallet and then select connect again, It connects straight away with no messages or popups etc on my metamask wallet, is this expected?

2023-09-11 10:29 UTC, bwallacee commented
If I try to scroll down on the withdraw assets list, it flashes and brings me back up to the top. Meaning I am unable to select any assets.
https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/ae89ece1-099c-4c2e-a16b-2092bddb2fa2

2023-09-11 10:54 UTC, bwallacee commented
I have raised a new issue for a withdraw scroll as it's happening on the deal ticket also:
https://github.com/vegaprotocol/frontend-monorepo/issues/4741

2023-09-11 12:21 UTC, bwallacee commented
Should we add new specs within this PR?

2023-09-11 22:07 UTC, mattrussell36 commented
> @macqbat On the withdraws page, if I disconnect my etherum wallet and then select connect again, It connects straight away with no messages or popups etc on my metamask wallet, is this expected?

@bwallacee this is expected. Because the wallet already allowed connection to this website it doesn't require you to confirm the connection a second time

2023-09-11 22:16 UTC, mattrussell36 commented
@macqbat @bwallacee 

I've added a single spec for each page to capture the setting the asset via the assetId query param. I don't think we need additional specs as everything else works exactly the same as when the component is opened in the sidebar.

2023-09-19 06:15 UTC, merged