chore: add handle of autosizing selected columns
vegaprotocol/frontend-monorepo pull request #4859
Opened 2023-09-22 14:02 UTC by macqbat

# Related issues 🔗

Closes #4792

# Description ℹ️

Add parameter to `useDataGridEvents` hook for handling autosizing on given columns

# Demo 📺

![Screenshot 2023-09-22 at 16 00 47](https://github.com/vegaprotocol/frontend-monorepo/assets/338931/b0f212e2-2cda-4672-9eb1-3e1f9f9bad4c)
vs
![Screenshot 2023-09-22 at 16 01 57](https://github.com/vegaprotocol/frontend-monorepo/assets/338931/a3ac55d4-6476-453b-828f-451effe6cbd2)

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2023-09-26 09:32 UTC, MadalinaRaicu approved these changes

2023-09-26 09:33 UTC, MadalinaRaicu commented
Please LMK when you make these changes for `main`

2023-09-26 13:20 UTC, daro-maj requested changes
Issue is visible for positions:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/df01381f-a066-4f33-a685-aa3b2ac017ef)

2023-09-26 17:55 UTC, mattrussell36 commented
@daro-maj can you verify if the issue is there after clearing local storage? If you've resized this manually it will persist. I can't recreate the issue.

2023-09-27 09:09 UTC, daro-maj approved these changes

2023-09-28 14:17 UTC, closed without merging