feat(trading): add funding payment history
vegaprotocol/frontend-monorepo pull request #4989
Opened 2023-10-05 16:03 UTC by bglownia

# Related issues 🔗

Closes #4915

# Description ℹ️

Add funding payment history to trade grid and portfolio

# Demo 📺

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1754247/325cac5b-2fbe-4af3-84ec-a2894fbeaa85)

2023-10-06 12:55 UTC, jeremyletang approved these changes

2023-10-06 13:00 UTC, guoguojin approved these changes

2023-10-06 13:12 UTC, pscott31 approved these changes

2023-10-09 09:08 UTC, MadalinaRaicu approved these changes

2023-10-09 10:49 UTC, daro-maj approved these changes

2023-10-09 11:20 UTC, daro-maj requested changes
Fills and Funding payments tab are showing as one 
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/652d9e37-500e-4c9b-928c-c5f3b2f806e9)

2023-10-09 14:59 UTC, merged