chore(trading): deposit test to jest
vegaprotocol/frontend-monorepo pull request #5036
Opened 2023-10-12 14:50 UTC by bwallacee

Moving deposit cypress tests to jest.

2023-10-12 15:00 UTC, daro-maj approved these changes

2023-10-12 21:19 UTC, mattrussell36 requested changes

2023-10-12 21:19 UTC, mattrussell36 commented on libs/accounts/src/lib/accounts-table.spec.tsx
> +    const depositButton = container.querySelector('[data-testid="deposit"');
Use screen, and getbyTestId

```suggestion
  const depositButton = screen.getByTestId('deposit')
```

2023-10-12 21:19 UTC, mattrussell36 commented on libs/accounts/src/lib/accounts-table.spec.tsx
> +      fireEvent.click(depositButton);
Please use userEvent unless theres a good reason not to
```suggestion
    await userEvent.click(depositButton);
```

2023-10-12 21:19 UTC, mattrussell36 commented on libs/accounts/src/lib/accounts-table.spec.tsx
> +    if (depositButton) {
We should avoid conditions in test.

screen.getByTestId will fail if the button is not found

2023-10-16 18:44 UTC, mattrussell36 approved these changes

2023-10-16 18:44 UTC, merged