chore(trading): withdraw tests to jest
vegaprotocol/frontend-monorepo pull request #5109
Opened 2023-10-23 14:20 UTC by bwallacee

Closes: https://github.com/vegaprotocol/console-test/issues/180

2023-10-23 14:39 UTC, MadalinaRaicu approved these changes

2023-10-23 14:44 UTC, daro-maj approved these changes

2023-10-23 23:13 UTC, mattrussell36 requested changes

2023-10-23 23:13 UTC, mattrussell36 commented on libs/withdraws/src/lib/withdraw-manager.spec.tsx
> +      await screen.getByTestId('connect-eth-wallet-btn')
getByTestId does not return a promise

2023-10-23 23:13 UTC, mattrussell36 commented on libs/withdraws/src/lib/withdraw-manager.spec.tsx
>      fireEvent.change(screen.getByLabelText('Asset'), {
(non blocking): Might be worth updating to userEvent

2023-10-23 23:13 UTC, mattrussell36 commented on libs/withdraws/src/lib/withdraw-manager.spec.tsx
> +    fireEvent.click(screen.getByTestId('use-maximum'));
(non blocking): can we use userEvent

2023-10-24 21:40 UTC, mattrussell36 approved these changes

2023-10-25 07:45 UTC, merged