Feat/smart contracts update
vegaprotocol/frontend-monorepo pull request #536
Opened 2022-06-09 15:17 UTC by dexturr

# Related issues 🔗

Closes #483 

# Description ℹ️

Adds the ability to use the new or old bridge contracts. The old one will need ot be used on the token site for mainnet until after mainnet has the new smart contracts enabled.

2022-06-09 16:04 UTC, mattrussell36 requested changes
Couple things to change here. Looks good, though I don't much like how we use collateral bridge and collateral bridge new. I think I would prefer to rename the current one to collateral-bridge-deprecated. Also I wonder if we can look into Jeremy's suggestion on slack

2022-06-09 16:04 UTC, mattrussell36 commented on apps/token/src/routes/withdraw/index.tsx
> +        useNewContract={Flags.USE_NEW_CONTRACTS}
chore (blocking): Can we rename this one too `isNewContract`

2022-06-09 16:26 UTC, dexturr commented on libs/smart-contracts/src/contracts/collateral-bridge.ts
>    constructor(
I think I'd prefer to add a deprecated decorator, which we can use everywhere. Will do this 👍

2022-06-09 16:28 UTC, mattrussell36 approved these changes

2022-06-10 08:30 UTC, sam-keen approved these changes

2022-06-10 08:30 UTC, sam-keen commented on libs/withdraws/src/lib/use-withdraw.spec.tsx
> +      query: ERC20_APPROVAL_QUERY_NEW,
Chore (non-blocking): ideally the tests should cover both contracts

2022-06-10 09:54 UTC, MadalinaRaicu approved these changes

2022-06-10 10:36 UTC, merged