chore(trading): update generic data provider
vegaprotocol/frontend-monorepo pull request #5431
Opened 2023-12-04 14:56 UTC by MadalinaRaicu

# Related issues 🔗

Closes N/A

# Description ℹ️ & Technical 👨‍🔧

- [x] update generic data provider pagination object to contain `last` field
- [x] when using `last` we can get the most recent records from the API
Note: this should be used since there is a limit between 1k and 5k records that can be retrieved (i.e. candles query)

2023-12-04 19:42 UTC, mattrussell36 requested changes

2023-12-04 19:42 UTC, mattrussell36 commented on libs/trades/src/lib/trades-data-provider.ts
> +    // first: MAX_TRADES,
Delete  this

2023-12-05 10:21 UTC, MadalinaRaicu commented on libs/trades/src/lib/trades-data-provider.ts
> +    // first: MAX_TRADES,
```suggestion
```

2023-12-06 04:48 UTC, mattrussell36 approved these changes

2023-12-06 12:32 UTC, merged