fix(trading): remove quadratic slippage factor
vegaprotocol/frontend-monorepo pull request #5641
Opened 2024-01-18 17:16 UTC by MadalinaRaicu

# Related issues 🔗

Closes #5551

# Description ℹ️

Remove quadratic slippage factor from market info.

2024-01-18 23:48 UTC, mattrussell36 approved these changes

2024-01-19 08:18 UTC, daro-maj requested changes
Please revert quadratic slippage factor in explorer and governance tests, currently they are failing and this is probably related to https://github.com/vegaprotocol/vega/issues/10343

2024-01-19 14:17 UTC, MadalinaRaicu commented on apps/governance-e2e/src/fixtures/proposals/new-market.json
> +    "quadraticSlippageFactor": "0.0",
```suggestion
    "quadraticSlippageFactor": "0",
```

2024-01-19 14:17 UTC, MadalinaRaicu commented on apps/governance-e2e/src/fixtures/proposals/successor-market.json
> +    "quadraticSlippageFactor": "0.0",
```suggestion
    "quadraticSlippageFactor": "0",
```

2024-01-19 14:18 UTC, MadalinaRaicu commented on apps/governance-e2e/src/fixtures/proposals/update-market.json
> +  "quadraticSlippageFactor": "0.0",
```suggestion
  "quadraticSlippageFactor": "0",
```

2024-01-20 21:35 UTC, daro-maj approved these changes

2024-01-22 10:17 UTC, jeremyletang approved these changes

2024-01-22 10:17 UTC, merged