feat(markets): new price monitoring bounds panel
vegaprotocol/frontend-monorepo pull request #5996
Opened 2024-03-13 14:06 UTC by asiaznik

# Related issues 🔗

Closes #[Issue number here]

# Description ℹ️

* removes redundant accordion items
* replaces price monitoring parameters with a visual representation of the bounds

# Demo 📺

<img width="337" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/f19465d5-6e49-4aeb-b5ab-829aff964794">

# Technical 👨‍🔧

N/A

2024-03-13 15:32 UTC, JonRay15 commented
So ... just asked Barney abotu this ... and he says that these seemingly logically identical bounds are actually like a "chain" of identical auctions. 

So in this example below that is a string of 5 x 60s auctions that will be triggered if price moves by more than whatever a horizon of 120 implies. The idea being that if the price has corrected in auction after the first minute you would come out of auction, but if it had not the auction would continue for another minute and so on all the way up to a max of 5 mins.  The idea of this is to avoid cases where a price move immediately triggers a big auction that you cant get out of even if the price in auction has corrected itself. 

How would your new implementation handle this? I cant tell which market you're trying to show in the screenshot, is it the Eigen one?  I guess what it should be doing is recognising logical groups and then showing something like "Will trigger 5 x 60s auctions as long as the price remains outside tolerated boudns" or something...

<img width="258" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/89918817/44ace548-417f-41bc-906e-98eeb444973b">

2024-03-14 10:05 UTC, mattrussell36 requested changes

2024-03-14 10:18 UTC, asiaznik commented on libs/utils/src/lib/use-duration.ts
> +export const useDuration = (mode: 'normal' | 'compact' = 'normal') => {
Fair enough

2024-03-14 15:30 UTC, daro-maj approved these changes

2024-03-15 11:10 UTC, mattrussell36 approved these changes

2024-03-15 16:22 UTC, merged