feat(deal-ticket): change min and max leverage
vegaprotocol/frontend-monorepo pull request #5998
Opened 2024-03-13 15:07 UTC by bglownia

# Related issues 🔗

Closes #5943

2024-03-13 16:07 UTC, daro-maj requested changes
switching leverage does not work if level is below 1
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/891f8763-0ea2-4940-8436-365e6a370e75)

2024-03-14 08:06 UTC, daro-maj approved these changes

2024-03-14 09:52 UTC, mattrussell36 approved these changes

2024-03-14 16:09 UTC, MadalinaRaicu approved these changes

2024-03-14 16:09 UTC, merged