fix(positions): rework of the liquidation tooltip
vegaprotocol/frontend-monorepo pull request #6070
Opened 2024-03-21 11:56 UTC by asiaznik

# Related issues 🔗

Closes #6019 

# Description ℹ️

* removed dependency od positions status
* checks the latest trades for specific market and party to deduce if a positions has been liquidated
* changes words
* fixes randomly failing tests

# Demo 📺

<img width="641" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/8d8b3d3f-0a1f-4f4f-a6d7-0d1458527db3">

# Technical 👨‍🔧

N/A

2024-03-21 13:08 UTC, bwallacee commented
@asiaznik I have to refresh the page in order to see the warning icon.

Also I wonder if we should change the 0 from being green:
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/f4e8754e-61d4-4dc2-a197-54ea04efd86d)

2024-03-21 14:34 UTC, bwallacee approved these changes

2024-03-21 14:54 UTC, mattrussell36 requested changes

2024-03-21 14:54 UTC, mattrussell36 commented on libs/positions/src/hooks/use-latest-trades.ts
> +const latestTradesDataProvider = makeDataProvider<
Why not use the trades data provider we already have? Why not add partyIds/marketIds and pagination as variables for the data provider?

Then we can only get the single last trade for the user?

2024-03-22 09:48 UTC, mattrussell36 approved these changes

2024-03-22 13:36 UTC, merged