feat(trading): game results
vegaprotocol/frontend-monorepo pull request #6130
Opened 2024-03-28 11:52 UTC by asiaznik

# Related issues 🔗

Closes #6061 
Closes #6114 

# Description ℹ️

* adds new game results page
* determines rank based on `rewardEarned`, ignores `rank` from API
* removes "Cumulative..." column from team results view

# Demo 📺

![image](https://github.com/vegaprotocol/frontend-monorepo/assets/1980305/5954969f-120e-42dc-b4be-df84862a1735)

# Technical 👨‍🔧

N/A

2024-03-28 14:15 UTC, MadalinaRaicu approved these changes

2024-04-02 12:42 UTC, bwallacee approved these changes

2024-04-02 14:21 UTC, guoguojin approved these changes

2024-04-02 14:27 UTC, mattrussell36 requested changes

2024-04-02 14:27 UTC, mattrussell36 commented on apps/trading/components/rewards-container/reward-card.tsx
> +    return clickable(
This is essentially a component but written as a 'normal' function. Please wrap it with normal component syntax or just Link

2024-04-02 14:27 UTC, mattrussell36 commented on libs/i18n/src/locales/en/trading.json
> +  "Visit the team's page.": "Visit the team's page.",
can you put this alphabetically please

2024-04-02 14:27 UTC, mattrussell36 commented on apps/trading/components/rewards-container/reward-card.tsx
> +            // 'grid grid-cols-4 grid-rows-2'
Tidy this please

2024-04-03 08:18 UTC, mattrussell36 approved these changes

2024-04-04 10:55 UTC, merged