fix(trading): increase market selector medium width
vegaprotocol/frontend-monorepo pull request #6152
Opened 2024-04-02 15:15 UTC by MadalinaRaicu

# Related issues 🔗

Closes #6028 

# Description ℹ️

The best way to **allow more space for market codes in the market selector** is to increase the overall medium width. 

# Demo 📺
<img width="1127" alt="Screenshot 2024-04-02 at 16 11 32" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/8d4a646f-fa5f-4104-9054-adbf73c346da">

vs 
<img width="1675" alt="Screenshot 2024-04-02 at 15 55 08" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/100992f9-5fe6-4a3c-bf19-6aeb7147d462">

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2024-04-02 16:53 UTC, mattrussell36 requested changes
The column header not longer aligns for 24h volume. It might just need text align right

2024-04-03 11:41 UTC, bwallacee commented
On mobile we still can't see if its a points market. Are we ok with this?
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/133853298/3d6b3952-b32c-4519-bf28-facd43f01cf3)

2024-04-04 11:14 UTC, MadalinaRaicu commented
> The column header not longer aligns for 24h volume. It might just need text align right



> The column header not longer aligns for 24h volume. It might just need text align right

fixed 
<img width="1032" alt="Screenshot 2024-04-04 at 12 11 48" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/0f410bf1-1292-442d-9946-7121f58c964a">
<img width="618" alt="Screenshot 2024-04-04 at 12 12 15" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/ee049be6-dc86-463d-a66f-ff199b627b4c">

2024-04-08 11:57 UTC, bwallacee approved these changes

2024-04-09 11:11 UTC, mattrussell36 approved these changes

2024-04-09 13:47 UTC, merged