feat: add a toast for liquidation notification
vegaprotocol/frontend-monorepo pull request #6568
Opened 2024-06-18 15:09 UTC by asiaznik

# Related issues 🔗

Closes #6055

# Description ℹ️

* adds toast that notifies about a position liquidation

# Demo 📺

# Technical 👨‍🔧

N/A

2024-06-20 09:04 UTC, mattrussell36 requested changes

2024-06-20 09:04 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.ts
> +  const onRejection = useCallback(
Use of useCallback here is pointless

2024-06-20 09:11 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.ts
> +  const rawValue = LocalStorage.getItem(LOCAL_STORAGE_KEY);
On second thought, do we even need local storage? I'm struggling to see the benefit of using it

2024-06-20 09:31 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.tsx
> +      const position = document.querySelector(
Dont like this. If we move to a persisted zustand store we can access it in the positions table

2024-06-20 09:32 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.tsx
> +  const onRejection = useCallback(
Pointless useCallback

2024-06-20 09:34 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.tsx
> +      if (ignore) return;
The ignore needs to be used inside the async callbacks to properly ignore 'stale' requests. This is another reason to just use the generated hook, which should handle race conditions if the fetch is invoked twice rapidly

2024-06-20 09:37 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.ts
> +  const rawValue = LocalStorage.getItem(LOCAL_STORAGE_KEY);
You can disregard the above comment, it makes sense to me now

2024-06-21 11:20 UTC, mattrussell36 approved these changes

2024-06-21 11:20 UTC, mattrussell36 commented on apps/trading/lib/hooks/use-position-closeout-notification.tsx
> +      name: 'seen_close_out_positions_toasts',
`vega_` prefix

2024-06-21 12:27 UTC, asiaznik commented on apps/trading/lib/hooks/use-position-closeout-notification.tsx
> +      name: 'seen_close_out_positions_toasts',
```suggestion
      name: 'vega_seen_close_out_positions_toasts',
```

2024-06-21 13:15 UTC, mattrussell36 approved these changes

2024-06-21 13:15 UTC, merged