fix: asset emblem chain logo
vegaprotocol/frontend-monorepo pull request #6579
Opened 2024-06-20 12:13 UTC by MadalinaRaicu

# Related issues 🔗

Closes N/A

# Description ℹ️

Adjust asset emblem chain logo.

# Demo 📺

<img width="493" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/1f756ae8-0932-47dc-9f47-f12b9d8a1eb0">

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2024-06-20 12:19 UTC, mattrussell36 approved these changes

2024-06-20 13:51 UTC, daro-maj approved these changes

2024-06-20 13:53 UTC, daro-maj requested changes
mobile is broken
![image](https://github.com/vegaprotocol/frontend-monorepo/assets/119658839/f23a4975-8a57-4f5f-b2c6-c5d7f14db05a)

2024-06-20 20:24 UTC, MadalinaRaicu commented
> mobile is broken 

thanks, fixed

<img width="493" alt="image" src="https://github.com/vegaprotocol/frontend-monorepo/assets/16125548/ebdd42aa-b5a6-43a1-937b-94a68b10c5ca">

2024-06-21 09:23 UTC, asiaznik approved these changes

2024-06-21 10:14 UTC, daro-maj approved these changes

2024-06-21 10:33 UTC, merged