fix: fee table label changes
vegaprotocol/frontend-monorepo pull request #6736
Opened 2024-07-31 10:54 UTC by dexturr

# Related issues 🔗

Closes #[Issue number here]

# Description ℹ️

A description of what this PR does. This should be non-dev readable. Technical stuff should go in the technical section below.

# Demo 📺

Gif/video/images of new/corrected functionality if applicable

# Technical 👨‍🔧

Details of technical implementation that reviewers may need to be aware of, if applicable.

2024-07-31 11:45 UTC, mattrussell36 requested changes

2024-07-31 11:45 UTC, mattrussell36 commented on libs/i18n/src/locales/en/trading.json
> +  "Taker fee after discount": "Taker fee after discount",
Can you move these so the file is kept alphabetical

2024-07-31 11:45 UTC, mattrussell36 commented on apps/trading/components/fees-container/market-fees.tsx
> +          cellRenderer: ({ value }: { value: string }) => (
I'd just use the cellClass property rather than a cellRenderer

2024-07-31 13:46 UTC, JonRay15 commented
Missing a few things

- Taker fee BEFORE discount wants to go to the left to become the second column
- Also I notice that we dont show the % symbole on the infra / maker / taker fee before discount
- And we wanted some way to emphasise the taker fee after discount .... maybe make it bold?  Or highlight the cell? or provide some extra border on the column?  Something to emphasise that it is really the key thing to worry about

![image](https://github.com/user-attachments/assets/b125555e-a1df-49c4-b949-d8831c04fb6e)

2024-08-01 11:47 UTC, mattrussell36 approved these changes

2024-08-05 08:29 UTC, edd approved these changes

2024-08-06 08:31 UTC, merged