chore(trading): usdt arb only via squid, non usdt arb deposit notific…
vegaprotocol/frontend-monorepo pull request #6737
Opened 2024-07-31 15:44 UTC by asiaznik

…ation

# Related issues 🔗

Closes #6688 

# Description ℹ️

* allows only USDT Arb to be deposited via Squid
* displays notification when trying to deposit non USDT Arb asset

# Demo 📺

![Screenshot 2024-07-31 at 17 40 26](https://github.com/user-attachments/assets/01317a52-c397-470a-a510-d1c2e749299a)
![Screenshot 2024-07-31 at 17 40 39](https://github.com/user-attachments/assets/7799b92a-c947-48e5-8f5c-4100e1c68cc1)

2024-07-31 16:21 UTC, mattrussell36 requested changes

2024-07-31 16:21 UTC, mattrussell36 commented on apps/trading/lib/utils/is-asset-usdt-arb.ts
> +    asset.symbol.toLowerCase() === 'usdt' &&
We've run into clashes of symbol before. Though its very unlikely on mainnet, I'd prefer if we just had the arb usd asset ID hardcoded in a config file and we used that, we'd then only need to check the id

2024-07-31 16:21 UTC, mattrussell36 commented on apps/trading/components/deposit-container/deposit-container.tsx
> +            <Notification
We are moving away from this component in forms. Can we instead render text similar to TradingInputError but in a warning (orange) color? Perhaps a new TradingInputWarning component, or perhaps TradingInputError could be changed to InputFeedback with a variant prop

2024-08-01 11:46 UTC, mattrussell36 approved these changes

2024-08-06 08:30 UTC, JonRay15 commented
Warning is displayed ... tick

![image](https://github.com/user-attachments/assets/4d20ab7b-8043-4d04-998a-22a48b372cef)

On squid we have a locked "receive" as expected. 

![image](https://github.com/user-attachments/assets/95173a37-0c0a-4982-911e-528afd5b055d)

I wonder if we should have some extra explanation here?

Currently we say "To ensure users enjoy the cheapest fees possible this mode only supports deposits into Arbitrum assets"

We should change this to "This form only supports deposits in Arbitrum USDT since the majority of markets on Vega settle in this asset.  If you wish to deposit a different asset please use the normal deposit flow."

2024-08-06 09:03 UTC, merged