feat(trading, governance, explorer): single color scheme
vegaprotocol/frontend-monorepo pull request #6748
Opened 2024-08-06 07:56 UTC by mattrussell36

# Related issues 🔗

TBD

# Description ℹ️

- Allow apps to set the colors via their stylesheets with single variables for light and dark, using the -gs- (grayscale) name.
- Remove `dark:` color prefixes as they are no longer needed

2024-08-07 13:41 UTC, edd commented
# Explorer TX filter broken by this PR
<img width="706" alt="Screenshot 2024-08-07 at 14 40 09" src="https://github.com/user-attachments/assets/840212b8-44b4-402c-b649-6cb5358c020d">

## Should look more like
<img width="850" alt="Screenshot 2024-08-07 at 14 40 56" src="https://github.com/user-attachments/assets/41267ee7-1019-4406-80ef-1e9944624d47">

2024-08-07 13:54 UTC, edd requested changes
There are a few spots where, in light mode, block explorer light grey backgrounds hav become too dark to be readable. See https://github.com/vegaprotocol/frontend-monorepo/pull/6748#issuecomment-2273506383

2024-08-08 09:21 UTC, asiaznik approved these changes

2024-08-08 10:02 UTC, dexturr approved these changes

2024-08-08 11:13 UTC, merged