Feat/tx dialog handling
vegaprotocol/frontend-monorepo pull request #850
Opened 2022-07-22 16:31 UTC by mattrussell36

# Related issues 🔗

Closes #837 

# Description ℹ️

TBD

# Demo 📺

TBD

# Technical 👨‍🔧

TBD

2022-07-23 08:35 UTC, MadalinaRaicu requested changes

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/dialog/dialog.tsx
> +                  className={`text-h4 font-bold text-black-95 dark:text-white-95 mt-0 mb-6 capitalize ${titleClassNames}`}
```suggestion
                  className={`text-h4 font-bold text-black-95 dark:text-white-95 mt-0 mb-6  ${titleClassNames}`}
```

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/ui-toolkit/src/components/dialog/dialog.tsx
> +                  className={`text-h4 font-bold text-black-95 dark:text-white-95 mt-0 mb-6 capitalize ${titleClassNames}`}
all dialogs have now capitalized letters, and Pete will ask me to change that as it is not consistent with the rest of the console style 

<img width="821" alt="Screenshot 2022-07-23 at 10 13 04" src="https://user-images.githubusercontent.com/16125548/180596865-22216e02-e906-4f19-a56c-c324994b5847.png">


<img width="1207" alt="Screenshot 2022-07-23 at 10 12 56" src="https://user-images.githubusercontent.com/16125548/180596854-fd385a12-2f45-4b5e-84e6-af51d253f775.png">

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/wallet/src/vega-transaction-dialog/vega-transaction-dialog.tsx
> +const getIntent = (transaction: VegaTxState) => {
(blocking): pulled the branch and tested. there is still sth not working correctly yet, the order has failed and we have a rejection reason but still displaying successful intent of the dialog

<img width="1229" alt="Screenshot 2022-07-23 at 10 05 40" src="https://user-images.githubusercontent.com/16125548/180596958-e67bb035-6d37-4f05-a25e-5445aea7aa37.png">

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/orders/src/lib/order-hooks/use-order-cancel.tsx
> +import { useCallback, useEffect, useState } from 'react';
```suggestion
import { useCallback, useState } from 'react';
```

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/orders/src/lib/order-hooks/use-order-cancel.tsx
> +import { useCallback, useEffect, useState } from 'react';
useEffect not used

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/wallet/src/vega-transaction-dialog/vega-transaction-dialog.tsx
> +      <div data-testid={transaction.status}>
ok, so I have tried to follow the [designs]( https://www.figma.com/file/K49Nx7XfocShhHcwwQzQkm/Console-V2?node-id=1652%3A26053) in Figma. we need to be aware we are changing these as we can see. 



![image](https://user-images.githubusercontent.com/16125548/180597243-5ac618ba-4cc0-4917-9c91-7b2ac79399e8.png)


<img width="1225" alt="Transaction Complete" src="https://user-images.githubusercontent.com/16125548/180597226-1dd34327-bd2b-449a-963b-8b63636e74bb.png">


<img width="1211" alt="VEGA TRADING PORTFOLIO" src="https://user-images.githubusercontent.com/16125548/180597222-eeacf997-113b-445b-a2db-cf83c3babe04.png">

2022-07-23 08:35 UTC, MadalinaRaicu commented on libs/deal-ticket/src/components/deal-ticket-manager.tsx
> +  const { submit, transaction, finalizedOrder, reset, Dialog } =
```suggestion
  const { submit, transaction, finalizedOrder, Dialog } =
```

2022-07-25 11:56 UTC, edd approved these changes
👍 Reviewed together in person at the same time as #851. This encapsulation is neat and I like it.

2022-07-26 08:30 UTC, MadalinaRaicu approved these changes

2022-07-26 13:35 UTC, merged