fix: walletconnect does not work
vegaprotocol/frontend-monorepo pull request #935
Opened 2022-08-02 15:03 UTC by asiaznik

# Related issues 🔗

Closes #919

# Technical 👨‍🔧

Bug was caused by a `global` and not `globalThis` reference in `@walletconnect/socket-transport/dist/esm/index.js`. That's why there's a dirty `global = globalThis` added to the `env-config.js`

Fixing `global` issue revealed another with missing `Buffer` - *webpack@5+* doesn't include node's polyfills anymore hence I needed to add it manually to the `polyfills.ts`.

# Demo 📺

![image](https://user-images.githubusercontent.com/1980305/182407208-cf1508c1-a2ec-4a1c-b8e2-2416d4139de3.png)

2022-08-03 08:41 UTC, dexturr commented on apps/token/src/assets/env-config.js
> +global = globalThis;
chore (blocking): this solution won't work as this file is overrided when running in docker. Can we put this else where please?

2022-08-03 08:41 UTC, dexturr requested changes
small issue

2022-08-03 08:57 UTC, dexturr approved these changes

2022-08-03 13:13 UTC, mattrussell36 approved these changes

2022-08-03 13:56 UTC, merged

2022-08-11 09:07 UTC, AndyWhiteVega commented
Tested: Working fine