Feat/815 auction conditions
vegaprotocol/frontend-monorepo pull request #955
Opened 2022-08-05 12:02 UTC by notbot00

# Related issues 🔗

Closes #815 

# Description ℹ️

Add info in a tooltip for the market trading mode display.

# Demo 📺

<img width="661" alt="Screenshot 2022-08-05 at 13 00 05" src="https://user-images.githubusercontent.com/105208209/183073296-2b5a9d69-b385-4a1e-b36d-601f6049e788.png">
<img width="573" alt="Screenshot 2022-08-05 at 13 00 19" src="https://user-images.githubusercontent.com/105208209/183073306-66db1686-c4c2-47fd-9574-7363b8ced0f8.png">
<img width="437" alt="Screenshot 2022-08-05 at 13 00 27" src="https://user-images.githubusercontent.com/105208209/183073307-c414b045-aff8-4b09-9430-347a7d2d1f99.png">
<img width="724" alt="Screenshot 2022-08-05 at 13 00 42" src="https://user-images.githubusercontent.com/105208209/183073303-6bcbe930-9763-42ec-bc1c-222710c45690.png">

2022-08-05 12:05 UTC, notbot00 commented on apps/trading/components/trading-mode-tooltip/trading-mode-tooltip.tsx
> +  console.log(market);
```suggestion

```

2022-08-05 13:15 UTC, mattrussell36 requested changes

2022-08-05 13:15 UTC, mattrussell36 commented on apps/trading/components/trading-mode-tooltip/trading-mode-tooltip.tsx
> +            'This is the standard trading mode where trades are executed never orders are received.'
chore (blocking): This reads odd, typo?

2022-08-05 13:59 UTC, notbot00 commented on apps/trading/components/trading-mode-tooltip/trading-mode-tooltip.tsx
> +            'This is the standard trading mode where trades are executed never orders are received.'
```suggestion
            'This is the standard trading mode where trades are executed whenever orders are received.'
```

2022-08-05 13:59 UTC, notbot00 commented on apps/trading/components/trading-mode-tooltip/trading-mode-tooltip.tsx
> +            'This is the standard trading mode where trades are executed never orders are received.'
thanks for the catch!

2022-08-05 14:12 UTC, mattrussell36 approved these changes

2022-08-08 10:19 UTC, MadalinaRaicu approved these changes

2022-08-08 10:19 UTC, merged

2022-08-08 10:20 UTC, sam-keen approved these changes